<?php
include('../auth/check.php');
include('../config/db.php');
$sql="SELECT q.id,q.queue_number,q.queue_type,q.workflow_status,b.first_name,b.middle_name,b.last_name,b.ext_name,b.barangay,b.lgu,e.form_locked,e.eligibility_status,e.approved_cash_amount FROM queue_entries q JOIN beneficiaries b ON b.id=q.beneficiary_id LEFT JOIN eligibility_forms e ON e.queue_entry_id=q.id WHERE DATE(q.transaction_date)=CURDATE() AND q.workflow_status IN ('WAITING_STEP_3','CALLED_STEP_3','HELD') ORDER BY CASE WHEN q.workflow_status='CALLED_STEP_3' THEN 0 WHEN q.queue_type='priority' THEN 1 ELSE 2 END,q.id ASC";
$result=$conn->query($sql);
function h($v){return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}
function fnm($r){return trim($r['last_name'].', '.$r['first_name'].' '.$r['middle_name'].' '.$r['ext_name']);}
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Confirmation</title><link rel="stylesheet" href="../assets/style.css"><link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"><style>.content{overflow:auto}.head{background:linear-gradient(135deg,#16a34a,#0f766e);color:white;padding:22px;margin:-22px -22px 18px}.head h1{margin:0}.toolbar{display:flex;gap:10px;margin-bottom:12px}.toolbar input,.toolbar select{height:42px;padding:0 12px;border:1px solid #cbd5e1;border-radius:8px}.card{background:white;border:1px solid #d6dce8;border-radius:12px;overflow:auto}.tbl{width:100%;border-collapse:collapse}.tbl th,.tbl td{padding:12px;border-bottom:1px solid #e5e7eb;text-align:left;white-space:nowrap}.tbl th{background:#f8fafc;font-size:12px;text-transform:uppercase}.prio td{background:#fff7ed}.held td{background:#fef2f2}.qprio{color:#c2410c;font-weight:900}.badge{padding:5px 9px;border-radius:999px;background:#e5e7eb;font-size:11px;font-weight:900}.amt{font-weight:900;color:#166534}.actions{display:flex;gap:6px}.ib{width:38px;height:38px;border:0;border-radius:8px;color:white;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;cursor:pointer}.ib span{font-size:19px}.call{background:#10b981}.paid{background:#16a34a}.cancel{background:#ef4444}.off{opacity:.35;pointer-events:none}.pager{display:flex;gap:6px;justify-content:flex-end;padding:12px}.pg{border:1px solid #cbd5e1;background:white;border-radius:7px;padding:7px 10px;cursor:pointer}</style></head><body><div class="app"><main class="main"><section class="content"><div class="head"><h1>Confirmation / Payout [Step 3]</h1><p>Call assessed beneficiaries and mark payout as paid.</p></div><div class="toolbar"><input id="s" placeholder="Search"><select id="t"><option value="">All Types</option><option value="priority">PRIO</option><option value="regular">PAL</option></select><select id="st"><option value="">All Status</option><option value="WAITING_STEP_3">Waiting</option><option value="CALLED_STEP_3">Called</option><option value="HELD">Held</option></select></div><div class="card"><table class="tbl"><thead><tr><th>Queue</th><th>Name</th><th>Barangay/LGU</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody id="rows">
<?php if($result): while($r=$result->fetch_assoc()): $isPrio=$r['queue_type']==='priority'; $isHeld=$r['workflow_status']==='HELD'; $isCalled=$r['workflow_status']==='CALLED_STEP_3'; $isWaiting=$r['workflow_status']==='WAITING_STEP_3'; $gis=intval($r['form_locked']??0)===1 && ($r['eligibility_status']??'')==='Eligible' && floatval($r['approved_cash_amount']??0)>0; ?>
<tr class="data <?php echo $isHeld?'held':($isPrio?'prio':''); ?>" data-type="<?php echo h($r['queue_type']); ?>" data-status="<?php echo h($r['workflow_status']); ?>"><td class="<?php echo $isPrio?'qprio':''; ?>"><?php echo h($r['queue_number']); ?></td><td><?php echo h(fnm($r)); ?></td><td><?php echo h($r['barangay']); ?>/<?php echo h($r['lgu']); ?></td><td class="amt"><?php echo $gis?'₱'.number_format(floatval($r['approved_cash_amount']),2):'No amount'; ?></td><td><span class="badge"><?php echo h($r['workflow_status']); ?></span></td><td><div class="actions"><form method="POST" action="../api/call_queue.php"><input type="hidden" name="queue_id" value="<?php echo intval($r['id']); ?>"><input type="hidden" name="counter_number" value="1"><button class="ib call <?php echo !$isWaiting?'off':''; ?>" title="Call"><span class="material-icons">campaign</span></button></form><form method="POST" action="../api/mark_paid.php" onsubmit="return confirm('Mark this queue as paid?');"><input type="hidden" name="queue_id" value="<?php echo intval($r['id']); ?>"><input type="hidden" name="counter_number" value="1"><button class="ib paid <?php echo (!$isCalled||!$gis)?'off':''; ?>" title="Paid"><span class="material-icons">payments</span></button></form><form method="POST" action="../api/cancel_queue.php"><input type="hidden" name="queue_id" value="<?php echo intval($r['id']); ?>"><input type="hidden" name="redirect" value="../staff/confirmation_screen.php"><button class="ib cancel" title="Cancel"><span class="material-icons">close</span></button></form></div></td></tr>
<?php endwhile; endif; ?>
</tbody></table><div class="pager" id="p"></div></div></section></main><?php include('sidebar.php'); ?></div><script>const rows=[...document.querySelectorAll('.data')],s=document.getElementById('s'),t=document.getElementById('t'),st=document.getElementById('st'),p=document.getElementById('p');let page=1,per=10;function apply(){let a=s.value.toLowerCase(),ty=t.value,sta=st.value,vis=rows.filter(r=>(!ty||r.dataset.type===ty)&&(!sta||r.dataset.status===sta)&&r.innerText.toLowerCase().includes(a));rows.forEach(r=>r.style.display='none');let pages=Math.max(1,Math.ceil(vis.length/per));if(page>pages)page=1;vis.slice((page-1)*per,page*per).forEach(r=>r.style.display='');p.innerHTML='';for(let i=1;i<=pages;i++){let b=document.createElement('button');b.className='pg';b.textContent=i;b.onclick=()=>{page=i;apply()};if(i===page){b.style.background='#16a34a';b.style.color='white'}p.appendChild(b)}}[s,t,st].forEach(e=>e.addEventListener('input',()=>{page=1;apply()}));apply();</script></body></html>
