<?php
include('../auth/check.php');
include('../config/db.php');

$queue_id = intval($_GET['queue_id'] ?? 0);
if ($queue_id <= 0) { header('Location: assessment_screen.php'); exit; }

$stmt = $conn->prepare("SELECT q.id AS queue_id,q.queue_number,q.workflow_status,q.beneficiary_id,b.beneficiary_code,b.first_name,b.middle_name,b.last_name,b.ext_name,b.contact_number,b.birthday_month,b.birthday_day,b.birthday_year,b.age,b.sex,b.region,b.province,b.city_municipality,b.barangay,b.lgu,b.national_id,b.household_id,b.program_type,b.sms_opt_in,b.is_pregnant FROM queue_entries q INNER JOIN beneficiaries b ON b.id=q.beneficiary_id WHERE q.id=? LIMIT 1");
$stmt->bind_param('i',$queue_id);
$stmt->execute();
$data = $stmt->get_result()->fetch_assoc();
if (!$data) { header('Location: assessment_screen.php'); exit; }

$stmt = $conn->prepare("SELECT * FROM eligibility_forms WHERE queue_entry_id=? OR beneficiary_id=? ORDER BY id DESC LIMIT 1");
$stmt->bind_param('ii',$queue_id,$data['beneficiary_id']);
$stmt->execute();
$form = $stmt->get_result()->fetch_assoc() ?: [];

function h($v){return htmlspecialchars($v ?? '',ENT_QUOTES,'UTF-8');}
function s($f,$k,$v){return (strval($f[$k] ?? '')===strval($v))?'selected':'';}
$is_locked = intval($form['form_locked'] ?? 0) === 1;
$name = trim($data['last_name'].', '.$data['first_name'].' '.$data['middle_name'].' '.$data['ext_name']);
$birthday = intval($data['birthday_month']).'/'.intval($data['birthday_day']).'/'.intval($data['birthday_year']);
$isPwd = intval($data['sms_opt_in'] ?? 0) === 1;
$isPregnant = intval($data['is_pregnant'] ?? 0) === 1;
$isSenior = intval($data['age'] ?? 0) >= 60;
$priorityText = $isPwd ? 'PWD Priority' : ($isPregnant ? 'Pregnant Priority' : ($isSenior ? 'Senior Priority' : 'Regular'));
$completeAddress = trim(($data['barangay'] ?? '').', '.($data['city_municipality'] ?? '').', '.($data['province'] ?? '').', '.($data['region'] ?? ''), ', ');
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Assessment Form</title><link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"><link rel="stylesheet" href="../assets/style.css"><style>
body{background:#f3f6fb}.wrap{padding:20px;flex:1;overflow:auto}.card{background:white;border:1px solid #d6dce8;border-radius:14px;padding:20px;margin-bottom:16px}h1{margin:0;color:#111827}.muted{color:#6b7280;margin:7px 0 0}.info{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.info div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;padding:12px}.info span{display:block;color:#64748b;font-size:11px;font-weight:900;text-transform:uppercase;margin-bottom:4px}.info strong{color:#111827;word-break:break-word}.wide{grid-column:span 2}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.field{display:flex;flex-direction:column}.field label{font-size:13px;font-weight:900;color:#374151;margin-bottom:6px}input,select,textarea{min-height:44px;padding:10px 12px;border:1px solid #cbd5e1;border-radius:9px;font-size:14px;background:white}textarea{min-height:78px;resize:vertical}.full{grid-column:1/-1}.actions{display:flex;gap:10px;margin-top:18px;flex-wrap:wrap}.btn{border:0;text-decoration:none;padding:12px 18px;border-radius:9px;font-weight:900;cursor:pointer}.save{background:#2563eb;color:white}.approve{background:#16a34a;color:white}.back{background:#374151;color:white}.lock{display:inline-block;padding:8px 12px;border-radius:999px;font-weight:900;margin-top:12px}.locked{background:#dcfce7;color:#166534}.draft{background:#fef3c7;color:#92400e}.priority{background:#fff7ed!important;border-color:#fed7aa!important;color:#9a3412!important}@media(max-width:900px){.grid,.info{grid-template-columns:1fr}.wide{grid-column:span 1}}
</style></head><body><div class="app"><main class="main"><section class="wrap">
<div class="card"><h1>GIS / Assessment Form</h1><p class="muted">Beneficiary details below are pulled exactly from the beneficiary record.</p><div class="lock <?php echo $is_locked?'locked':'draft'; ?>"><?php echo $is_locked?'Approved and Locked':'Draft / Not yet approved'; ?></div>
<div class="info">
<div><span>Queue</span><strong><?php echo h($data['queue_number']); ?></strong></div><div><span>Beneficiary Code</span><strong><?php echo h($data['beneficiary_code']); ?></strong></div><div class="wide"><span>Client Name</span><strong><?php echo h($name); ?></strong></div>
<div><span>Birthday</span><strong><?php echo h($birthday); ?></strong></div><div><span>Age / Sex</span><strong><?php echo intval($data['age']); ?> / <?php echo h($data['sex']); ?></strong></div><div><span>Contact Number</span><strong><?php echo h($data['contact_number'] ?: '-'); ?></strong></div><div class="<?php echo ($isPwd||$isPregnant||$isSenior)?'priority':''; ?>"><span>Priority Status</span><strong><?php echo h($priorityText); ?></strong></div>
<div><span>PWD</span><strong><?php echo $isPwd?'Yes':'No'; ?></strong></div><div><span>Pregnant</span><strong><?php echo $isPregnant?'Yes':'No'; ?></strong></div><div><span>ID Presented</span><strong><?php echo h($data['national_id'] ?: '-'); ?></strong></div><div><span>Household ID</span><strong><?php echo h($data['household_id'] ?: '-'); ?></strong></div>
<div><span>Program / Assistance</span><strong><?php echo h($data['program_type'] ?: '-'); ?></strong></div><div><span>Region</span><strong><?php echo h($data['region']); ?></strong></div><div><span>Province</span><strong><?php echo h($data['province']); ?></strong></div><div><span>City / Municipality</span><strong><?php echo h($data['city_municipality']); ?></strong></div><div class="wide"><span>Complete Address</span><strong><?php echo h($completeAddress); ?></strong></div>
</div></div>
<form class="card" method="POST" action="../api/save_eligibility.php">
<input type="hidden" name="queue_id" value="<?php echo intval($queue_id); ?>"><input type="hidden" name="beneficiary_id" value="<?php echo intval($data['beneficiary_id']); ?>">
<div class="grid">
<div class="field"><label>ID / Requirement Presented</label><select name="id_type_presented" <?php echo $is_locked?'disabled':''; ?> required><option value="">Select</option><option value="Government ID" <?php echo s($form,'id_type_presented','Government ID'); ?>>National/Government ID</option><option value="Barangay Certificate" <?php echo s($form,'id_type_presented','Barangay Certificate'); ?>>Barangay Certificate</option><option value="Senior Citizen ID" <?php echo s($form,'id_type_presented','Senior Citizen ID'); ?>>Senior Citizen ID</option><option value="PWD ID" <?php echo s($form,'id_type_presented','PWD ID'); ?>>PWD ID</option><option value="No Valid ID" <?php echo s($form,'id_type_presented','No Valid ID'); ?>>No Valid ID</option></select></div>
<div class="field"><label>Masterlist Match</label><select name="matches_masterlist" <?php echo $is_locked?'disabled':''; ?> required><option value="Yes" <?php echo s($form,'matches_masterlist','Yes'); ?>>Yes</option><option value="No" <?php echo s($form,'matches_masterlist','No'); ?>>No</option></select></div>
<div class="field"><label>Beneficiary Type</label><select name="beneficiary_type" <?php echo $is_locked?'disabled':''; ?> required><option value="">Select</option><option value="Indigent" <?php echo s($form,'beneficiary_type','Indigent'); ?>>Indigent</option><option value="Senior Citizen" <?php echo s($form,'beneficiary_type','Senior Citizen'); ?>>Senior Citizen</option><option value="PWD" <?php echo s($form,'beneficiary_type','PWD'); ?>>PWD</option><option value="Pregnant" <?php echo s($form,'beneficiary_type','Pregnant'); ?>>Pregnant</option><option value="Solo Parent" <?php echo s($form,'beneficiary_type','Solo Parent'); ?>>Solo Parent</option><option value="Medical Assistance" <?php echo s($form,'beneficiary_type','Medical Assistance'); ?>>Medical Assistance</option><option value="Educational Assistance" <?php echo s($form,'beneficiary_type','Educational Assistance'); ?>>Educational Assistance</option></select></div>
<div class="field"><label>Source of Income</label><select name="income_source" <?php echo $is_locked?'disabled':''; ?> required><option value="">Select</option><option value="BSNS" <?php echo s($form,'income_source','BSNS'); ?>>BSNS - Business</option><option value="SLRY" <?php echo s($form,'income_source','SLRY'); ?>>SLRY - Salary</option><option value="NONE" <?php echo s($form,'income_source','NONE'); ?>>None</option></select></div>
<div class="field"><label>Household Members</label><select name="household_members" <?php echo $is_locked?'disabled':''; ?> required><option value="">Select</option><?php for($i=1;$i<=10;$i++): ?><option value="<?php echo $i; ?>" <?php echo s($form,'household_members',$i); ?>><?php echo $i; ?></option><?php endfor; ?><option value="11" <?php echo s($form,'household_members','11'); ?>>11+</option></select></div>
<div class="field"><label>Dependents</label><select name="dependents" <?php echo $is_locked?'disabled':''; ?> required><option value="">Select</option><?php for($i=0;$i<=8;$i++): ?><option value="<?php echo $i; ?>" <?php echo s($form,'dependents',$i); ?>><?php echo $i; ?></option><?php endfor; ?><option value="9" <?php echo s($form,'dependents','9'); ?>>9+</option></select></div>
<div class="field"><label>Requirement Status</label><select name="supporting_documents" <?php echo $is_locked?'disabled':''; ?> required><option value="Complete" <?php echo s($form,'supporting_documents','Complete'); ?>>Complete</option><option value="Incomplete" <?php echo s($form,'supporting_documents','Incomplete'); ?>>Incomplete</option><option value="For Verification" <?php echo s($form,'supporting_documents','For Verification'); ?>>For Verification</option></select></div>
<div class="field"><label>Eligibility Status</label><select name="eligibility_status" <?php echo $is_locked?'disabled':''; ?> required><option value="Pending Review" <?php echo s($form,'eligibility_status','Pending Review'); ?>>Pending Review</option><option value="Eligible" <?php echo s($form,'eligibility_status','Eligible'); ?>>Eligible</option><option value="Not Eligible" <?php echo s($form,'eligibility_status','Not Eligible'); ?>>Not Eligible</option></select></div>
<div class="field"><label>Approved Amount</label><select name="approved_cash_amount" <?php echo $is_locked?'disabled':''; ?> required><option value="">Select</option><?php foreach([1000,2000,3000,5000] as $amt): ?><option value="<?php echo $amt; ?>" <?php echo floatval($form['approved_cash_amount'] ?? 0)==$amt?'selected':''; ?>>₱<?php echo number_format($amt); ?></option><?php endforeach; ?></select></div>
<div class="field full"><label>Reason / Remarks</label><select name="assistance_reason" <?php echo $is_locked?'disabled':''; ?> required><option value="Financial Assistance" <?php echo s($form,'assistance_reason','Financial Assistance'); ?>>Financial Assistance</option><option value="Medical Assistance" <?php echo s($form,'assistance_reason','Medical Assistance'); ?>>Medical Assistance</option><option value="Educational Assistance" <?php echo s($form,'assistance_reason','Educational Assistance'); ?>>Educational Assistance</option><option value="Emergency Assistance" <?php echo s($form,'assistance_reason','Emergency Assistance'); ?>>Emergency Assistance</option></select></div>
<input type="hidden" name="id_reference_note" value="Beneficiary record verified"><input type="hidden" name="monthly_income" value="0"><input type="hidden" name="already_received_payout" value="No"><input type="hidden" name="receiving_other_assistance" value="No"><input type="hidden" name="remarks" value="Minimal GIS assessment">
</div><div class="actions"><?php if(!$is_locked): ?><button class="btn save" type="submit" name="action" value="save">Save Draft</button><button class="btn approve" type="submit" name="action" value="approve">Approve / Lock</button><?php endif; ?><a class="btn back" href="assessment_screen.php">Back</a></div>
</form></section></main><?php include('sidebar.php'); ?></div></body></html>
