<?php
include('../auth/check.php');
include('../config/db.php');
$sql="SELECT q.queue_number,q.queue_type,q.workflow_status,q.counter_number,b.first_name,b.middle_name,b.last_name,b.ext_name,b.barangay,b.lgu FROM queue_entries q JOIN beneficiaries b ON b.id=q.beneficiary_id WHERE DATE(q.transaction_date)=CURDATE() AND q.workflow_status NOT IN ('PAID','CANCELLED') ORDER BY CASE WHEN q.queue_type='priority' THEN 0 ELSE 1 END,q.id ASC";
$result=$conn->query($sql);
function h($v){return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}
function fnm($r){return trim($r['last_name'].', '.$r['first_name'].' '.$r['middle_name'].' '.$r['ext_name']);}
function dest($s){if($s==='WAITING_STEP_2')return 'Assessment Waiting Area';if($s==='CALLED_STEP_2')return 'Assessment Counter';if($s==='WAITING_STEP_3')return 'Confirmation Waiting Area';if($s==='CALLED_STEP_3')return 'Confirmation / Payout Counter';if($s==='HELD')return 'Help Desk / Requirements';return 'Ask staff';}
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Guard Check</title><link rel="stylesheet" href="../assets/style.css"><link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"><style>.content{overflow:auto}.head{background:linear-gradient(135deg,#334155,#0f172a);color:white;padding:22px;margin:-22px -22px 18px}.head h1{margin:0}.search{width:100%;height:48px;padding:0 14px;border:1px solid #cbd5e1;border-radius:10px;margin-bottom:14px}.card{background:white;border:1px solid #d6dce8;border-radius:12px;overflow:auto}.tbl{width:100%;border-collapse:collapse}.tbl th,.tbl td{padding:12px;border-bottom:1px solid #e5e7eb;text-align:left}.tbl th{background:#f8fafc;font-size:12px;text-transform:uppercase}.prio td{background:#fff7ed}.qprio{color:#c2410c;font-weight:900}.badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#dbeafe;color:#1e40af;font-size:11px;font-weight:900}.go{font-weight:900;color:#0f172a}</style></head><body><div class="app"><main class="main"><section class="content"><div class="head"><h1>Guard Check</h1><p>Search queue number or name to tell the beneficiary where to proceed.</p></div><input id="s" class="search" placeholder="Search queue/name/barangay/LGU"><div class="card"><table class="tbl"><thead><tr><th>Queue</th><th>Name</th><th>Barangay/LGU</th><th>Status</th><th>Direction</th></tr></thead><tbody>
<?php if($result): while($r=$result->fetch_assoc()): $isPrio=$r['queue_type']==='priority'; ?>
<tr class="data <?php echo $isPrio?'prio':''; ?>"><td class="<?php echo $isPrio?'qprio':''; ?>"><?php echo h($r['queue_number']); ?></td><td><?php echo h(fnm($r)); ?></td><td><?php echo h($r['barangay']); ?>/<?php echo h($r['lgu']); ?></td><td><span class="badge"><?php echo h($r['workflow_status']); ?></span></td><td class="go"><?php echo h(dest($r['workflow_status'])); ?></td></tr>
<?php endwhile; endif; ?>
</tbody></table></div></section></main><?php include('sidebar.php'); ?></div><script>const s=document.getElementById('s'),rows=[...document.querySelectorAll('.data')];s.addEventListener('input',()=>{let v=s.value.toLowerCase();rows.forEach(r=>r.style.display=r.innerText.toLowerCase().includes(v)?'':'none')});</script></body></html>
